#PSG712 16M USB+Adbyby+Aliddns+SS+在线文件管理+远程下载
name: Build Padavan

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot \
        cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget
    - name: Clone source code
      run: |
        git clone --depth=1 https://github.com/lemontreenm/rt-n56u.git /opt/rt-n56u
        cd /opt/rt-n56u/toolchain-mipsel
        sh dl_toolchain.sh
        mkdir -p /opt/images/
    - name: Build Firmware
      env:
        TNAME: PSG712
      run: |
        cd /opt/rt-n56u/trunk
        if [ ! -f configs/templates/$TNAME.config ] ; then
        echo "configs/templates/$TNAME.config not found "
        exit 1
        fi
        cp -f configs/templates/$TNAME.config .config
        sed -i 's/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=n/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=y/g' .config
        ################################################################################################
        #因不同型号配置功能不一样，所以先把配置项删除，如果你自己要添加其他的，也要写上删除这一条，切记！！！
        ################################################################################################
        sed -i '/CONFIG_FIRMWARE_INCLUDE_MENTOHUST/d' .config #删除配置项MENTOHUST
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT/d' .config #删除配置项SCUTCLIENT
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS/d' .config #删除配置项SS plus+
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SSSERVER/d' .config #删除配置项SS server
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER/d' .config #删除配置项DNSFORWARDER
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ADBYBY/d' .config #删除配置项adbyby plus+
        sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPC/d' .config #删除配置项内网穿透FRPC
        sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPS/d' .config #删除配置项内网穿透FRPS
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TUNSAFE/d' .config #删除配置项TUNSAFE
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ALIDDNS/d' .config #删除配置项阿里DDNS
        sed -i '/CONFIG_FIRMWARE_INCLUDE_XUPNPD/d' .config #删除用于 IPTV 的 XUPNP配置项
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DOGCOM/d' .config #删除用于 Drcom 的工具配置项
        sed -i '/CONFIG_FIRMWARE_INCLUDE_MINIEAP/d' .config #删除可用于锐捷的 eap 客户端配置项
        sed -i '/CONFIG_FIRMWARE_INCLUDE_NJIT_CLIENT/d' .config #删除南工网络客户端配置项
        sed -i '/CONFIG_FIRMWARE_ENABLE_USB/d' .config #删除配置项 USB
        sed -i '/CONFIG_FIRMWARE_ENABLE_UFSD/d' .config #删除配置项UFSD
        sed -i '/CONFIG_FIRMWARE_ENABLE_FAT/d' .config #删除配置项 FAT格式支持
        sed -i '/CONFIG_FIRMWARE_ENABLE_EXFAT/d' .config #删除配置项 EXFAT格式支持
        sed -i '/CONFIG_FIRMWARE_ENABLE_EXT2/d' .config #删除配置项 EXT2格式支持
        sed -i '/CONFIG_FIRMWARE_ENABLE_EXT3/d' .config #删除配置项 EXT3格式支持
        sed -i '/CONFIG_FIRMWARE_ENABLE_EXT4/d' .config #删除配置项 EXT4格式支持
        sed -i '/CONFIG_FIRMWARE_ENABLE_FUSE/d' .config #删除配置项 文件夹支持
        sed -i '/CONFIG_FIRMWARE_INCLUDE_UVC/d' .config #删除配置项 摄像头支持
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SERIAL/d' .config #删除配置项 
        sed -i '/CONFIG_FIRMWARE_INCLUDE_AUDIO/d' .config #删除配置项 音频设备支持
        sed -i '/CONFIG_FIRMWARE_INCLUDE_LPRD/d' .config #删除配置项 打印机支持
        sed -i '/CONFIG_FIRMWARE_INCLUDE_U2EC/d' .config #删除配置项 外网远程打印
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TRANSMISSION/d' .config #删除配置项TRANSMISSION
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TRANSMISSION_WEB_CONTROL/d' .config #删除配置项TRANSMISSION_WEB_CONTROL
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ARIA/d' .config #删除配置项Aria
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ARIA_WEB_CONTROL/d' .config #删除配置项Aria的网页配置
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TCPDUMP/d' .config #删除配置项 
        sed -i '/CONFIG_FIRMWARE_INCLUDE_HDPARM/d' .config #删除配置项 硬盘休眠
        sed -i '/CONFIG_FIRMWARE_INCLUDE_PARTED/d' .config #删除配置项 GPT硬盘支持
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SMBD/d' .config #删除配置项 Smaba1.0支持
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SMBD36/d' .config #删除配置项 Smaba3.6支持
        sed -i '/CONFIG_FIRMWARE_INCLUDE_OPENSSH/d' .config #删除SSH功能配置项
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SFTP/d' .config #删除SFTP功能配置项
        sed -i '/CONFIG_FIRMWARE_INCLUDE_HTOP/d' .config #删除配置项 HTOP
        sed -i '/CONFIG_FIRMWARE_INCLUDE_NANO/d' .config #删除配置项 NANO
        sed -i '/CONFIG_FIRMWARE_INCLUDE_IPERF3/d' .config #删除配置项 IPERF3
        sed -i '/CONFIG_FIRMWARE_WEBUI_HIDE_VPN/d' .config #删除配置项 HIDE_VPN
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SMARTDNS/d' .config 
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SRELAY/d' .config 
        sed -i 's/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=n/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=y/g' .config
        ######################################################################
        #以下选项是定义你需要的功能（y=集成,n=忽略），重新写入到.config文件
        ######################################################################
        echo "CONFIG_FIRMWARE_INCLUDE_MENTOHUST=n" >> .config #MENTOHUST
        echo "CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT=n" >> .config #SCUTCLIENT
        echo "CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS=n" >> .config #SS plus+
        echo "CONFIG_FIRMWARE_INCLUDE_SSOBFS=n" >> .config # simple-obfs混淆插件
        echo "CONFIG_FIRMWARE_INCLUDE_SSSERVER=n" >> .config #SS server
        echo "CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER=n" >> .config #DNSFORWARDER
        echo "CONFIG_FIRMWARE_INCLUDE_ADBYBY=y" >> .config #adbyby plus+
        echo "CONFIG_FIRMWARE_INCLUDE_FRPC=n" >> .config #内网穿透FRPC
        echo "CONFIG_FIRMWARE_INCLUDE_FRPS=n" >> .config #内网穿透FRPS
        echo "CONFIG_FIRMWARE_INCLUDE_TUNSAFE=n" >> .config #TUNSAFE
        echo "CONFIG_FIRMWARE_INCLUDE_ALIDDNS=y" >> .config #阿里DDNS
        echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNS=n" >> .config #smartdns
        echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNSBIN=n" >> .config #smartdns二进制文件
        echo "CONFIG_FIRMWARE_INCLUDE_V2RAY=n" >> .config #集成v2ray执行文件（3.8M左右)，如果不集成，会从网上下载下来执行，不影响正常使用
        echo "CONFIG_FIRMWARE_INCLUDE_TROJAN=n" >> .config #集成trojan执行文件(1.1M左右)，PSG712内存太小无法启动，所以没有集成的必要
        echo "CONFIG_FIRMWARE_INCLUDE_KOOLPROXY=n" >> .config #KP广告过滤
        echo "CONFIG_FIRMWARE_INCLUDE_CADDY=n" >> .config #在线文件管理服务，PSG712内存太小无法启动，所以没有集成的必要
        echo "CONFIG_FIRMWARE_INCLUDE_CADDYBIN=n" >> .config #集成caddu执行文件，此文件有13M,请注意固件大小。如果不集成，会从网上下载下来执行，不影响正常使用
        echo "CONFIG_FIRMWARE_INCLUDE_ADGUARDHOME=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_SRELAY=n" >> .config #可以不集成
        echo "CONFIG_FIRMWARE_INCLUDE_WYY=n" >> .config #网易云解锁
        echo "CONFIG_FIRMWARE_INCLUDE_WYYBIN=n" >> .config #网易云解锁GO版本执行文件（4M多）注意固件超大小,不集成会自动下载
        echo "CONFIG_FIRMWARE_INCLUDE_XUPNPD=n" >> .config #去除用于 IPTV 的 XUPNP        
        echo "CONFIG_FIRMWARE_INCLUDE_DOGCOM=n" >> .config  #去除用于 Drcom 的工具
        echo "CONFIG_FIRMWARE_INCLUDE_MINIEAP=n" >> .config  #去除可用于锐捷的 eap 客户端
        echo "CONFIG_FIRMWARE_INCLUDE_NJIT_CLIENT=n" >> .config  #去除南工网络客户端
        echo "CONFIG_FIRMWARE_ENABLE_USB=y" >> .config  #添加USB支持
        echo "CONFIG_FIRMWARE_ENABLE_UFSD=y" >> .config  #添加USB支持
        echo "CONFIG_FIRMWARE_ENABLE_FAT=y" >> .config  #添加USB支持
        echo "CONFIG_FIRMWARE_ENABLE_EXFAT=y" >> .config  #添加USB支持
        echo "CONFIG_FIRMWARE_ENABLE_EXT2=n" >> .config  #添加USB支持
        echo "CONFIG_FIRMWARE_ENABLE_EXT3=n" >> .config  #添加USB支持
        echo "CONFIG_FIRMWARE_ENABLE_EXT4=y" >> .config  #添加USB支持
        echo "CONFIG_FIRMWARE_ENABLE_FUSE=y" >> .config  #添加USB支持
        echo "CONFIG_FIRMWARE_INCLUDE_UVC=n" >> .config  #添加USB支持
        echo "CONFIG_FIRMWARE_INCLUDE_SRELAY=y" >> .config #可以不集成
        echo "CONFIG_FIRMWARE_INCLUDE_AUDIO=n" >> .config  #添加USB支持
        echo "CONFIG_FIRMWARE_INCLUDE_LPRD=y" >> .config  #添加USB支持
        echo "CONFIG_FIRMWARE_INCLUDE_U2EC=y" >> .config  #添加USB支持
        echo "CONFIG_FIRMWARE_INCLUDE_TCPDUMP=n" >> .config  #添加USB支持
        echo "CONFIG_FIRMWARE_INCLUDE_HDPARM=y" >> .config  #添加USB支持
        echo "CONFIG_FIRMWARE_INCLUDE_PARTED=n" >> .config  #添加USB支持
        echo "CONFIG_FIRMWARE_INCLUDE_SMBD=y" >> .config  #添加smaba支持
        echo "CONFIG_FIRMWARE_INCLUDE_SMBD36=y" >> .config  #添加SMBD3.6功能
        echo "CONFIG_FIRMWARE_INCLUDE_TRANSMISSION=n" >> .config #集成远程下载
        echo "CONFIG_FIRMWARE_INCLUDE_TRANSMISSION_WEB_CONTROL=n" >> .config #集成远程下载的配置网页
        echo "CONFIG_FIRMWARE_INCLUDE_ARIA=n" >> .config #Aria
        echo "CONFIG_FIRMWARE_INCLUDE_ARIA_WEB_CONTROL=n" >> .config #Aria的网页控制
        echo "CONFIG_FIRMWARE_INCLUDE_OPENSSH=y" >> .config  #SSH功能
        echo "CONFIG_FIRMWARE_INCLUDE_SFTP=n" >> .config  #去除SFTP功能
        echo "CONFIG_FIRMWARE_INCLUDE_HTOP=n" >> .config  #去除HTOP功能
        echo "CONFIG_FIRMWARE_INCLUDE_NANO=n" >> .config  #去除NANO功能
        echo "CONFIG_FIRMWARE_INCLUDE_IPERF3=y" >> .config  #调价IPERF3功能
        echo "CONFIG_FIRMWARE_WEBUI_HIDE_VPN=n" >> .config  #VPN功能不隐藏
        echo "CONFIG_FIRMWARE_INCLUDE_ZEROTIER=n" >> .config #zerotier ~1.3M
        #########################################################################################
        #自定义添加其它功能请参考源码configs/templates/目录下的config文件。按照上面的格式添加即可
        #格式如下：
        #sed -i '/自定义项/d' .config
        #echo "自定义项=y" >> .config
        #########################################################################################
        sudo ./clear_tree
        sudo ./build_firmware_modify $TNAME 0
        sudo mv -f images/*.trx /opt/images/
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Padavan-packages
        path: /opt/images
